version: '3.8'

services:

  db:
    image: postgres:14
    container_name: db
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: backend
    restart: always
    depends_on:
      - db
      - redis
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=countdown_project.settings
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - ./server/staticfiles:/app/staticfiles  # ✅ Ensure static files persist

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "4200:80"

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    depends_on:
      - frontend
      - backend
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"

volumes:
  postgres_data:
